version: '3'

services:
  myspa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../spa:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
