# Nginx tabanlı resmi imajı kullan
FROM nginx:alpine

# Çalışma dizinini /usr/share/nginx/html olarak belirle
WORKDIR /usr/share/nginx/html

# Lokal spa dizinindeki tüm dosyaları /usr/share/nginx/html'e kopyala

# Nginx konfigürasyon dosyasını değiştir

# Nginx'i çalıştır
CMD ["nginx", "-g", "daemon off;"]
